C:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex> & C:/Users/benjm/AppData/Local/Programs/Python/Python310/python.exe c:/Us
ers/benjm/git/codeHistoriesPythonProjects/Pokedex/pokedex.pyX
X
X
X
X
X
X
DevTools listening on ws://127.0.0.1:64135/devtools/browser/31c2c9dd-edd9-4e27-aeb1-97ad6588cbf1
> c:\users\benjm\git\codehistoriespythonprojects\pokedex\pokedex.py(60)scrape()
-> row_data = row.find_elements(By.TAG_NAME, "td")X
(Pdb) row (Pdb) ro[25128:3764:0623/001006.167:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error
 -101X
X   -101X[3
832:12076:0623/001008.239:ERROR:device_event_log_impl.cc(214)] [00:10:08.238] USB: usb_device_handle_win.cc:1048 Failed to read desc
riptor from node connection: A device attached to the system is not functioning. (0x1F)X
X[25128:3764:0623/001009.056:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -201
Xcontinue
X> c:\users\benjm\git\codehistoriespythonprojects\pokedex\pokedex.py(62)scrape()
-> poke_data["name"] = row_data[1].find_element(By.TAG_NAME, "a").textX
(Pdb)Xpoke_date a
X{}
(Pdb)Xquit()
XException in Tkinter callback
Traceback (most recent call last):X
  File "C:\Users\benjm\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__X
    return self.func(*args)X
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 81, in get_pokemonX
    poke_data = scrape(int(poke_id))X
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 62, in scrapeX
    poke_data["name"] = row_data[1].find_element(By.TAG_NAME, "a").textX
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 62, in scrapeX
    poke_data["name"] = row_data[1].find_element(By.TAG_NAME, "a").textX
  File "C:\Users\benjm\AppData\Local\Programs\Python\Python310\lib\bdb.py", line 90, in trace_dispatchX
    return self.dispatch_line(frame)X
  File "C:\Users\benjm\AppData\Local\Programs\Python\Python310\lib\bdb.py", line 115, in dispatch_lineX
    if self.quitting: raise BdbQuitX
bdb.BdbQuitX
XTraceback (most recent call last):
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 148, in <module>X
X    main()
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 141, in mainX
    run_gui()  # gui is initially empty, prompts user to enter a pokemon IDX
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 130, in run_guiX
    window.mainloop()  #TODO PROBLEM: this is blockingX
  File "C:\Users\benjm\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1458, in mainloopX
    self.tk.mainloop(n)X
KeyboardInterruptX
X    if self.quitting: raise BdbQuitX
bdb.BdbQuitX
Traceback (most recent call last):X
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 148, in <module>X
    main()X
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 141, in mainX
    run_gui()  # gui is initially empty, prompts user to enter a pokemon IDX
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 130, in run_guiX
    window.mainloop()  #TODO PROBLEM: this is blockingX
  File "C:\Users\benjm\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1458, in mainloopX
    self.tk.mainloop(n)X
KeyboardInterruptX
XPS 