C:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex> & C:/Users/benjm/AppData/Local/Programs/Python/Python310/python.exe c:/Us
ers/benjm/git/codeHistoriesPythonProjects/Pokedex/pokedex.pyX
XException in Tkinter callback
XTraceback (most recent call last):
  File "C:\Users\benjm\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__X
    return self.func(*args)X
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 75, in get_pokemonX
    poke_data = scrape(int(poke_id))X
ValueError: invalid literal for int() with base 10: ''X
X
DevTools listening on ws://127.0.0.1:64368/devtools/browser/d3944e6f-de53-4fa5-b73b-a5496438d161X
X{'name': 'Venusaur', 'types': ['GRASS', 'POISON'], 'hp': '80', 'attack': '82', 'defense': '83', 'special attack': '100', 'special de
fense': '100', 'speed': '80'}X
Xers/benjm/git/codeHistoriesPythonProjects/Pokedex/pokedex.pyX
Exception in Tkinter callbackX
Traceback (most recent call last):X
  File "C:\Users\benjm\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__X
    return self.func(*args)X
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 75, in get_pokemonX
    poke_data = scrape(int(poke_id))X
ValueError: invalid literal for int() with base 10: ''X
X
DevTools listening on ws://127.0.0.1:64368/devtools/browser/d3944e6f-de53-4fa5-b73b-a5496438d161X
{'name': 'Venusaur', 'types': ['GRASS', 'POISON'], 'hp': '80', 'attack': '82', 'defense': '83', 'special attack': '100', 'special de
fense': '100', 'speed': '80'}X
PS 